### ISSUE TITLE
Feather dependency only in runtime scope

### ISSUE THREAD

**Issue by noeppi-noeppi** [ParchmentMC/Librarian#3]
Currently the dependency to Feather is added to the POM only in `runtime`scope. However as there is a protected method that returns `VersionedMappingDataContainer` since #2, I think this should be changed to the `compile` scope.

**Comment by SizableShrimp** [comment]
The runtime scope is determined by gradle when building the pom. It is declared as implementation in the build.gradle. What is the issue?

**Comment by noeppi-noeppi** [comment]
Adding librarian as a dependency to another project won't add feather to the implementation configuration. This would be solved if the scope of the dependency was `compile` [here](https://maven.parchmentmc.org/org/parchmentmc/librarian/1.1.3/librarian-1.1.3.pom).

As described [here](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#dependency-scope), the `runtime` scope
> indicates that the dependency is not required for compilation, but is for execution.

For the compile scope:
> Compile dependencies are available in all classpaths of a project. Furthermore, those dependencies are propagated to dependent projects.

And as there is a protected method that is meant to be used by things depending on librarian that returns a feather class, feather should be propagated to dependent projects in my opinion.
