### ISSUE TITLE
Add support for Forge Loom

### ISSUE THREAD

**Issue by GlassSpirit** [ParchmentMC/Librarian#4]
Forge Loom is a replacement plugin to Forge Gradle, based on FabricMC Loom.
It would be great to use Parchment mappings with this tool.
https://docs.architectury.dev/docs/forge_loom/
https://github.com/architectury/architectury-loom

**Comment by SizableShrimp** [comment]
This is a non-issue. Forge Loom is a fork of FabricMC's Loom, which already supports Parchment mappings out of the box. If you need info on how to use it, see the pins in #fabric in the ParchmentMC discord. It works the same for Forge Loom.
