### ISSUE TITLE
Parchment is remapping record field/method names on Forge

### ISSUE THREAD

**Issue by Niko-sk2x** [ParchmentMC/Librarian#5]
~~I don't know whether the issue belongs in Librarian or here.~~ _issue was transferred from Parchment repository._

When using Parchment on ForgeGradle, parchment's `params.csv` ends up containing mapping entries for record field names, example part of `params.csv`:
```
p_106690_,pPartialTicks,
p_116066_,pLivingEntity,
p_116067_,pMatrixStack,
p_116068_,pPartialTickTime,
p_116064_,pEntity,
f_122766_,pKey,
f_122767_,pId,
f_122768_,pValue,
p_187059_,pParameters,
p_187060_,pPreset,
p_48466_,pSeed,
p_76213_,pLevel,
p_76214_,pPos,
```

Because of the way ForgeGradle applies mappings, it applies them regardless of which file they are in.
But [FML MCPNamingService](https://github.com/MinecraftForge/MinecraftForge/blob/335cb5edc4467a213a01a315e75aad5aa3569f34/fmlloader/src/main/java/net/minecraftforge/fml/loading/MCPNamingService.java#L54-L72) loads only `methods.csv` and `fields.csv` and ignores `params.csv` (because they shouldn't matter) making those mappings inaccessible through that API at runtime.

This breaks my [OptiFineDevTweaker](https://github.com/OpenCubicChunks/OptiFineDevTweaker) as it can't remap certain usages of records correctly.

Example class where I ran into it: `net.minecraft.world.level.block.state.properties.Property.Value`

**Comment by SizableShrimp** [comment]
This is definitely a Librarian issue and has to do with the special way that MCPConfig exports data for canonical record constructors. The parameter names for these constructors actually use the SRG field name to support recompilation. Fix incoming with explanation in comments.
