### ISSUE TITLE
I HAVE A PROBLEM WITH THE LOGGING FILES OF THE EXAMPLE MOD CLASS

### ISSUE THREAD

**Issue by AryamanTomer** [ParchmentMC/Librarian#6]
So I have a problem that says error: package com.mojang.logging does not exist
import com.mojang.logging.LogUtils;

I also apparently have a importing class that does not exist 
what do I do?

**Comment by SizableShrimp** [comment]
This is not related to Librarian at all. Please use a relevant Discord for your query. You may find [Modded MC's Discord](https://discord.gg/moddedmc) helpful.
