### ISSUE TITLE
Method where only parts of the parameters are mapped won't be processed

### ISSUE THREAD

**Issue by noeppi-noeppi** [ParchmentMC/Librarian#7]
If a method only has *some* but not all of its parameters mapped in the parchment data, none of the mapped parameters will be used to build the mappings zip file used by ForgeGradle. As an example, see [FormattedCharSink#accept](https://github.com/ParchmentMC/Parchment/blob/9379d14d9f6e40f8db0c9f5d366ed723f8539b2f/data/net/minecraft/util/FormattedCharSink.mapping#L2-L4) with parchment `2022.03.13`.

The problem is that in [ParchmentChannelProvider#populateParameters](https://github.com/ParchmentMC/Librarian/blob/4e1c71871f6753179761302c3418671f78c15ff6/src/main/java/org/parchmentmc/librarian/forgegradle/ParchmentChannelProvider.java#L231) size of the the result from [MethodData#getParameters](https://github.com/ParchmentMC/Feather/blob/d3e95d28363ac2af9aedcac3be0ccb0f69d18bd4/core/src/main/java/org/parchmentmc/feather/mapping/MappingDataContainer.java#L276) is compared with the amount of SRG parameters that method has. As `MethodData#getParameters` only contains entries for mapped parameters, this will only succeed, if *all* parameters of the method have been mapped in parchment.

The comment above that line tries to explain, why that check is necessary, however I still don't really understand the purpose. From my understanding, whenever `populateParameters` is called, the descriptors from the SRG mappings and the parchment export have already been compared, so it can be made sure that the method is the same and has the same amount of parameters. And I don't see a reason to not partially map the parameters. This would then require to access parameters through [MethodData#getParameter](https://github.com/ParchmentMC/Feather/blob/d3e95d28363ac2af9aedcac3be0ccb0f69d18bd4/core/src/main/java/org/parchmentmc/feather/mapping/MappingDataContainer.java#L287) instead of relying on the index in a list.

I would appreciate if you could explain the purpose of that equality check to me.

**Comment by SizableShrimp** [comment]
The SRG mapping data I load is at best a TSRGv2 file.
The indices stored for parameters in a TSRGv2 file are *not* the JVM indices.
They are just numbered starting from zero.
The index stored/used for ParameterData and MethodData *is* the JVM index.
So any methods using doubles or longs or whatever other edge case will have mismatched partially mapped parameters if I try to do a lookup with the int index from the SRG parameter.
And I don't really feel like implementing a mapper from normal SRG index to JVM index.
If you care to PR that and it works well, then I will probably look into merging it.
But I probably won't look into this myself, as it is annoying and not something that (to my knowledge) happens often in mapped Parchment methods.
